"""Build extractive summary hypernodes from a saved memory graph.

The summaries are provenance-preserving: they are assembled only from existing
fact/source snippets in the graph, not generated by an LLM.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hypermem.profile_centric_hypergraph import ProfileCentricHypergraphMemory  # noqa: E402
from hypermem.summary_hypernodes import build_summary_hypernodes, save_summary_hypernodes  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--memory-graph", required=True)
    parser.add_argument("--output", default="", help="Default: graph_dir/summary_hypernodes.json")
    parser.add_argument("--max-summary-tokens", type=int, default=48)
    parser.add_argument("--fact-group-size", type=int, default=4)
    parser.add_argument("--max-nodes-per-level", type=int, default=200)
    args = parser.parse_args()

    graph_path = Path(args.memory_graph)
    out_path = Path(args.output) if args.output else graph_path.parent / "summary_hypernodes.json"
    memory = ProfileCentricHypergraphMemory.load(graph_path)
    nodes = build_summary_hypernodes(
        memory,
        max_summary_tokens=args.max_summary_tokens,
        fact_group_size=args.fact_group_size,
        max_nodes_per_level=args.max_nodes_per_level,
    )
    save_summary_hypernodes(nodes, out_path)
    by_level = {}
    for node in nodes:
        by_level[node.level] = by_level.get(node.level, 0) + 1
    report = {
        "memory_graph": str(graph_path),
        "output": str(out_path),
        "num_summary_hypernodes": len(nodes),
        "by_level": by_level,
        "extractive_only": True,
        "fact_summary_always_source_backed": True,
        "topic_episode_summary_optional": True,
    }
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
